(define (logical-not signal)
  (cond ((= signal 0) 1)
        ((= signal 1) 0)
        (else (error "Invalid signal" s))))

(define (inverter input output)
  (define (invert-input)
    (let ((new-value (logical-not (get-signal input))))
      (after-delay inverter-delay (lambda () (set-signal! ouput new-value)))))
  (add-action! input invert-input)
  'ok)
