(define (variable? x) (symbol? x))
(define (same-variable x y)
  (and (variable? x) (variable? y) (eq? x y))
)
(define (make-sum x y)
  '(+ x y)
)
(define (make-product x y)
  '(* x y)
)
(define (sum? x)
  (and (pair? x) (eq? (car x) '+))
)
(define (addend s) (cadr s))
(define (augend s) (caddr s))
(define (product? x)
  (and (pair? x) (eq? (car x) '*))
)
(define (multiplier p) (cadr p))
(define (multiplicand p) (caddr p))
