(define (element-of-set? set x)
  (cond ((null? set) false)
        ((equal? x (car set)) true)
        (else (element-of-set? (cdr set) x))
  )
)

(define (adjoin-set x set)
  (if (element-of-set? set x)
      set 
      (cons x set)
  )
)

(define (intersection-set s1 s2)
  (cond ((or (null? s1) (null? s2)) '())
        ((element-of-set? s2 (car s1))
         (cons (car s1) (intersection-set (cdr s1) s2)))
        (else (intersection-set (cdr s1) s2))
  )
)

(define (union-set s1 s2)
  (cond ((null? s1) s2)
        ((null? s2) s1)
        ((element-of-set? s2 (car s1))
          (union-set (cdr s1) s2))
        (else (cons (car s1) (union-set (cdr s1) s2)))
  )
)

(define (adjoin-set-dup x set)
  (cons x set)
)

(define (union-set-dup s1 s2)
  (append s1 s2)
)
